#!/usr/bin/env python3
"""Fetch the broadsheet theme's web fonts (Fraunces + Newsreader) and bundle them.

Reproducible, pinned source for the self-contained `--embed-fonts` feature of
`render_explainer.py`. Downloads the woff2 files Google Fonts serves for the two
families (latin + latin-ext, roman + italic), writes them to the fonts dir with
deterministic names, and emits a `broadsheet-fonts.css` whose @font-face rules
reference the LOCAL files (preserving unicode-range subsetting). `--embed-fonts`
then inlines those local woff2 as base64 data URIs at render time.

Run this once to (re)populate the bundled fonts:

    python3 tools/fetch_broadsheet_fonts.py \
        --out templates/content-type-explainers/shared/fonts/broadsheet

Both families are licensed under the SIL Open Font License 1.1 (see OFL.txt in
the output dir); bundling is permitted.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
import urllib.request

# Pinned family queries — variable axes, italic, capped subsets kept small.
FAMILIES = {
    "Fraunces": "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..700;1,9..144,300..700&display=swap",
    "Newsreader": "https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap",
}
KEEP_SUBSETS = {"latin", "latin-ext"}
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# @font-face blocks in Google's CSS are each preceded by a `/* subset */` comment.
_BLOCK = re.compile(r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*(?P<face>@font-face\s*\{.*?\})", re.DOTALL)
_URL = re.compile(r"url\((https://[^)]+\.woff2)\)")


def _get(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req, timeout=30).read().decode()


def _download(url: str, dest: str) -> None:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    data = urllib.request.urlopen(req, timeout=30).read()
    with open(dest, "wb") as f:
        f.write(data)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True, help="output fonts dir")
    a = ap.parse_args(argv)
    os.makedirs(a.out, exist_ok=True)

    css_out: list[str] = []
    total = 0
    for family, url in FAMILIES.items():
        css = _get(url)
        for m in _BLOCK.finditer(css):
            subset = m.group("subset")
            if subset not in KEEP_SUBSETS:
                continue
            face = m.group("face")
            um = _URL.search(face)
            if not um:
                continue
            src = um.group(1)
            style = "italic" if "font-style: italic" in face else "roman"
            # Deterministic filename: family-subset-style-<8 hex of url>.woff2
            h = hashlib.sha256(src.encode()).hexdigest()[:8]
            fname = f"{family.lower()}-{subset}-{style}-{h}.woff2"
            _download(src, os.path.join(a.out, fname))
            total += 1
            css_out.append(face.replace(f"url({src})", f"url({fname})"))
            print(f"  {fname}", file=sys.stderr)

    css_path = os.path.join(a.out, "broadsheet-fonts.css")
    with open(css_path, "w") as f:
        f.write("/* Generated by tools/fetch_broadsheet_fonts.py — do not hand-edit.\n"
                "   Fraunces + Newsreader, SIL OFL 1.1. url() are local; --embed-fonts\n"
                "   inlines them as base64 data URIs. */\n")
        f.write("\n".join(css_out) + "\n")
    print(f"wrote {total} woff2 + {css_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
